config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :rooms, only: %i[show create], param: :title
  resources :messages, only: :create
  root "rooms#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :message, counter_cache: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :likes, dependent: :destroy

  scope :sorted, -> { order(:id) }
  validates :body, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages, -> { sorted }, dependent: :destroy
  before_create { self.title = SecureRandom.hex(3) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @new_message = current_user&.messages&.build(strong_params)
    
    if @new_message&.save
      @new_message.broadcast_append_to @new_message.room
    end
  end
  private

  def strong_params 
    params.require(:message).permit(:room_id, :body)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @new_room = Room.new
    @rooms = Room.all
  end
  
  def create
    @new_room = current_user&.rooms&.build

    if @new_room&.save
      @new_room.broadcast_append_to :rooms
    end
  end

  def show 
    @room = Room.find_by!(title: params[:title])
    @messages = Room.find_by!(title: params[:title])[:messages]
    @new_message = current_user&.messages&.build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  </head>

  <body>
 <div class="min-h-full">
  <nav class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <div class="flex items-center">
          <div class="flex-shrink-0">
             <a href="/">  
            <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          </a>
          </div>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <% if user_signed_in? %>
              <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete}, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"%>
              <% else %>
              <%= link_to "Sign in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"%>
              <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="md:hidden" id="mobile-menu">
      <div class="space-y-1 px-2 pt-2 pb-3 sm:px-3">
        <% if user_signed_in? %>
        <%= link_to "Sign out ", destroy_user_session_path, data: { "turbo-method": :delete}, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
        <% else %>
        <%= link_to "Sign in ", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
        <%= link_to "Sign up ", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
        <% end %>

    </div>
    </div>
  </nav>

  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Chat</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    <%= yield %>
    </div>
  </main>
</div>
  
  </body>
</html>

app/views/messages/_message.html.erb
<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg my-4 py-2 pl-1">
  <div class="flex flex-row">
    <div class="basis-1/12">...<%= l(message.created_at, format: :short) %></div>
    <div class="basis-3/12"><%= message.user.email %></div>
    <div class="basis-7/12"><%= message.body %></div>
  
  </div>
</div>

app/views/rooms/_room.html.erb
<%=link_to room.title, room_path(room.title), target: "_blank", rel: "noopener norefferer"%>

app/views/rooms/index.html.erb
<%= turbo_stream_from :rooms %>

<%= turbo_frame_tag :rooms do %>
  <%render @rooms%>
<% end %>
<% if user_signed_in? %>
  <%= form_with model: @new_room do |f| %>
      <%= f.submit "new room", class:'bg-red text-blue font-semibold hover:cursor-pointer py-2 px-4 border border-blue rounded'%>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>
<%= turbo_stream_from @messages %>
<%= turbo_stream_from [current_user, @room] %>

<div class="flex flex-col h-96 justify-between">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8" id="chat-container">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8" id="room_<%= @room.id %>_messages">
      <%= render partial: "messages/message", collection: @room.messages, locals: { user: current_user } %>
      <%= turbo_frame_tag :messages do %>
        <%= render @messages %>
      <% end %>
    </div>
  </div>
</div>

<%= form_with model: @new_message, data: { controller: "chat_refresh", action: "turbo:submit-end->chat_refresh#clearInput" } do |f| %>
    <%= f.text_field :body, autofocus: true, required: true, placeholder: "Your text", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
    <%= f.hidden_field :room_id, value: @room.id %>
<% end %>